### ISSUE TITLE
Fix GCP cloud vulnerabilities

### ISSUE THREAD

**Issue by marqueewinq** [synthesized-io/sdk-on-gcp#6]
https://support.synthesized.io/a/tickets/137
https://support.synthesized.io/a/tickets/140

---

# Summary
  The synthesized-sdk-service in GKE gave excessive authority when defining Service Account named "synthesized-sdk-service-1-serviceaccount-2580". Besides, this Service Account is mounted in a deployment named "synthesized-sdk-service-worker", witch makes it possible for attackers to raise rights to administrators.
# Detailed Analysis
I deployed synthesized-sdk-service in the marketplace of Google's GKE cluster.
The clusterrole named "synthesized-sdk-service-1:serviceAccount-r0" defines the "create" verb of "pods" and the "create" verb of "pods/exec". And this clusterrole is bound to the Service Account named "synthesized-sdk-service-1-serviceaccount-2580".
# Attacking Strategy
  If a malicious user controls a specific worker node which has the deployment mentioned above , or steals the Service Account token mentioned above. He/She can raise permissions to administrator level and control the whole cluster.
For example,
With the "create" verb of "pods", attacker can elevate privileges by creating a pod to mount and steal any Service Account he/she want.
# Mitigation Discussion
Developer could use the rolebinding instead of the clusterrolebinding to restrict permissions to namespace.
Developer could delete the "create" verb of "pod" and "pod/exec" defined in clusterrole.
# A few questions
Is it a real issue in synthesized-sdk-service?
If it's a real issue, can synthesized-sdk-service mitigate the risks following my suggestions discussed in the "mitigation discussion"?
If it's a real issue, does synthesized-sdk-service plan to fix this issue?

---

# Summary
 The synthesized-sdk-notebook-byol in GKE gave excessive authority when defining Service Account named "synthesized-sdk-notebook-byol-serviceaccount-dc07". Besides, this Service Account is mounted in a deployment named "synthesized-sdk-notebook-byol-1-sdk", witch makes it possible for attackers to raise rights to administrators.
# Detailed Analysis
    1. I deployed synthesized-sdk-notebook-byol in the marketplace of Google's GKE cluster.
    2. The clusterrole named "synthesized-sdk-notebook-byol-1:serviceAccount-r0" defines the "create" verb of "Pod/exec". And this clusterrole is bound to the Service Account named "synthesized-sdk-notebook-byol-serviceaccount-dc07".
# Attacking Strategy
 If a malicious user controls a specific worker node which has the deployment mentioned above , or steals the Service Account token mentioned above. He/She can raise permissions to administrator level and control the whole cluster.
# Mitigation Discussion
    • Developer could use the rolebinding instead of the clusterrolebinding to restrict permissions to namespace.
    • Developer could delete the "create" verb of "Pod/exec".
# A few questions
    • Is it a real issue in synthesized-sdk-notebook-byol?
    • If it's a real issue, can synthesized-sdk-notebook-byol mitigate the risks following my suggestions discussed in the "mitigation discussion"?
    • If it's a real issue, does synthesized-sdk-notebook-byol plan to fix this issue?

**Comment by marqueewinq** [comment]
We'll need to change `ClusterRole` to `Role` in https://github.com/synthesized-io/sdk-on-gcp/blob/main/schema.yaml#L44

**Comment by tomcarter23** [comment]
Closing as duplicate
